apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cellar.fullname" . }}
  labels:
    {{- include "cellar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cellar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cellar.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cellar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBIT_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBIT_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cellar.fullname" . }}
                  key: rabbitmq-password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodb-uri
                  name: {{ include "cellar.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
