apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cellar.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "cellar.labels" . | nindent 4 }}
    app.kubernetes.io/component: cellar
type: Opaque
data:
    rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
    mongodb-uri: {{ .Values.mongodb.uri | b64enc | quote }}
